services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # All secrets and environment variables are handled by Render
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      # note that this is just a template, as it's only used in "Swarm mode", there are no limit rsrcs if you're outside Swarm
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  app-network:
    driver: bridge
